import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import TheFooter from "@/components/TheFooter";
import TheHeader from "@/components/TheHeader";
import './globals.css'

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <TheHeader />
        <main className="container">{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
